/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import logica.EntradaLog;
import oovv.Entrada;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class MiDialogo extends javax.swing.JDialog {

    /**
     * Creates new form MiDialogo
     */
    public MiDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bIntroducir = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tfPalabra = new javax.swing.JTextField();
        jlTexto = new javax.swing.JLabel();
        jlPosicion = new javax.swing.JLabel();
        tfPosicion = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bIntroducir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bIntroducir.setText("Introducir");
        bIntroducir.setActionCommand("introducir");

        bCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setActionCommand("cancelar");

        tfPalabra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfPalabra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlTexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTexto.setText("Introduce una palabra para añadir:");

        jlPosicion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlPosicion.setText("Indica la posicion:");
        jlPosicion.setMinimumSize(new java.awt.Dimension(0, 0));

        tfPosicion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfPosicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPosicion.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(tfPalabra, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(tfPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIntroducir)
                    .addComponent(bCancelar))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MiDialogo dialog = new MiDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bIntroducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlPosicion;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JTextField tfPalabra;
    private javax.swing.JTextField tfPosicion;
    // End of variables declaration//GEN-END:variables

    public void setOyente(EntradaLog oyente) {
        bIntroducir.addActionListener(oyente);
        bCancelar.addActionListener(oyente);
    }

    public Entrada getEntrada() {
        return new Entrada(tfPalabra.getText(), Integer.parseInt(tfPosicion.getText()));
    }

    public void setAccion(String accion, List<String> listaPalabra) {
        if (accion.equals("desactivaPos")) {
            tfPosicion.setText(Integer.toString(listaPalabra.size()));
            jlPosicion.setEnabled(false);
            tfPosicion.setEnabled(false);
        }
        if (accion.equals("activaPos")) {
            tfPosicion.setText(Integer.toString(listaPalabra.size()));
            jlPosicion.setEnabled(true);
            tfPosicion.setEnabled(true);
        }
        if (accion.equals("activaIntercambio")) {
            tfPosicion.setText(Integer.toString(listaPalabra.size()));
            jlTexto.setText("Introduce la palabra a intercambiar:");
            jlPosicion.setText("Introduce su nueva posicion:");
            jlPosicion.setEnabled(true);
            tfPosicion.setEnabled(true);
        }

        if (accion.equals("activaBorrar")) {
            jlTexto.setText("Introduce la palabra a borrar:");
            jlPosicion.setText("Introduce la posicion a borrar:");
            tfPosicion.setText("-1");
        }
        if (accion.equals("activaSep")) {
            jlTexto.setText("Define los caracteres separadores:");
            tfPosicion.setText(Integer.toString(listaPalabra.size()));
            jlPosicion.setVisible(false);
            tfPosicion.setVisible(false);
        }
    }

}
