/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import logica.LogPrincipal;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bInicialesMayus = new javax.swing.JButton();
        bAñadir = new javax.swing.JButton();
        bInsertar = new javax.swing.JButton();
        bVisualizar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bQuitarRepetidas = new javax.swing.JButton();
        bVerLista = new javax.swing.JButton();
        bAñadirTodas = new javax.swing.JButton();
        bBorrarPalabrasTexto = new javax.swing.JButton();
        bTodoMayus = new javax.swing.JButton();
        bDefinirSeparadores = new javax.swing.JButton();
        bTodoMinus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPantalla = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bInicialesMayus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bInicialesMayus.setText("Inciales mayuscula");
        bInicialesMayus.setActionCommand("iniciales mayus");

        bAñadir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bAñadir.setText("Añadir palabra");
        bAñadir.setActionCommand("añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        bInsertar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bInsertar.setText("Insertar palabra");
        bInsertar.setActionCommand("insertar");

        bVisualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bVisualizar.setText("Ver palabra");
        bVisualizar.setActionCommand("intercambio");
        bVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarActionPerformed(evt);
            }
        });

        bBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bBorrar.setText("Borrar palabra");
        bBorrar.setActionCommand("borrar");

        bQuitarRepetidas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bQuitarRepetidas.setText("Quitar repetidas");
        bQuitarRepetidas.setActionCommand("quitar repetidas");

        bVerLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bVerLista.setText("Ver lista completa");
        bVerLista.setActionCommand("ver lista");

        bAñadirTodas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bAñadirTodas.setText("Añadir palabras texto");
        bAñadirTodas.setActionCommand("añadir palabras texto");

        bBorrarPalabrasTexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bBorrarPalabrasTexto.setText("Borrar palabras texto");
        bBorrarPalabrasTexto.setActionCommand("borrar palabras texto");

        bTodoMayus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bTodoMayus.setText("Todo mayusculas");
        bTodoMayus.setActionCommand("todo mayus");

        bDefinirSeparadores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bDefinirSeparadores.setText("Definir separadores");
        bDefinirSeparadores.setActionCommand("definir separaciones");

        bTodoMinus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bTodoMinus.setText("Todo minusculas");
        bTodoMinus.setActionCommand("todo minus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bTodoMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDefinirSeparadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBorrarPalabrasTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAñadirTodas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVerLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bQuitarRepetidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVisualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAñadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTodoMayus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bInicialesMayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bQuitarRepetidas)
                .addGap(24, 24, 24)
                .addComponent(bVerLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAñadirTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBorrarPalabrasTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDefinirSeparadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTodoMayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTodoMinus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bInicialesMayus)
                .addContainerGap())
        );

        taPantalla.setColumns(20);
        taPantalla.setRows(5);
        jScrollPane1.setViewportView(taPantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bAñadirTodas;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBorrarPalabrasTexto;
    private javax.swing.JButton bDefinirSeparadores;
    private javax.swing.JButton bInicialesMayus;
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bQuitarRepetidas;
    private javax.swing.JButton bTodoMayus;
    private javax.swing.JButton bTodoMinus;
    private javax.swing.JButton bVerLista;
    private javax.swing.JButton bVisualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPantalla;
    // End of variables declaration//GEN-END:variables

    public void setOyente(LogPrincipal oyente) {
        JButton[] losBotones = {bAñadir, bInsertar, bVisualizar, bBorrar, bQuitarRepetidas, bVerLista, bAñadirTodas,
            bBorrarPalabrasTexto, bDefinirSeparadores, bTodoMayus, bTodoMinus, bInicialesMayus};
        for (JButton boton : losBotones) {
            boton.addActionListener(oyente);
        }
    }

    public void borraPantalla() {
        taPantalla.setText("");
    }

    public void muestraLista(String cad) {
        taPantalla.append(cad);
    }
}
