/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import logica.LogPrincipal;
import oovv.Bola;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNuevoBombo = new javax.swing.JButton();
        bSacarNBolas = new javax.swing.JButton();
        bSacarBola = new javax.swing.JButton();
        bVaciarBombo = new javax.swing.JButton();
        bListarBolasBombo = new javax.swing.JButton();
        bListarBolasSacadas = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jpBolas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bNuevoBombo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bNuevoBombo.setText("Nuevo Bombo");
        bNuevoBombo.setActionCommand("nuevo bombo");

        bSacarNBolas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bSacarNBolas.setText("Sacar N bolas");
        bSacarNBolas.setActionCommand("sacar n bolas");

        bSacarBola.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bSacarBola.setText("Sacar bola");
        bSacarBola.setActionCommand("sacar bola");

        bVaciarBombo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bVaciarBombo.setText("Vaciar bombo");
        bVaciarBombo.setActionCommand("vaciar bombo");

        bListarBolasBombo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bListarBolasBombo.setText("Ver bolas bombo");
        bListarBolasBombo.setActionCommand("ver bolas bombo");

        bListarBolasSacadas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bListarBolasSacadas.setText("Ver bolas sacadas");
        bListarBolasSacadas.setActionCommand("ver bolas sacadas");

        bSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bSalir.setText("Salir");
        bSalir.setActionCommand("salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bNuevoBombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSacarNBolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSacarBola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bListarBolasBombo)
                            .addComponent(bListarBolasSacadas)
                            .addComponent(bVaciarBombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bListarBolasBombo, bListarBolasSacadas, bNuevoBombo, bSacarBola, bSacarNBolas, bVaciarBombo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bNuevoBombo)
                .addGap(13, 13, 13)
                .addComponent(bListarBolasBombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bListarBolasSacadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSacarBola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSacarNBolas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bVaciarBombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bNuevoBombo, bSacarNBolas});

        jpBolas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "BOMBO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBolas, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bListarBolasBombo;
    private javax.swing.JButton bListarBolasSacadas;
    private javax.swing.JButton bNuevoBombo;
    private javax.swing.JButton bSacarBola;
    private javax.swing.JButton bSacarNBolas;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bVaciarBombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpBolas;
    // End of variables declaration//GEN-END:variables

    public void setOyente(LogPrincipal oyente) {
        JButton[] losBotones = {bNuevoBombo, bListarBolasBombo, bListarBolasSacadas, bSacarBola, bSacarNBolas,
            bVaciarBombo, bSalir};
        for (JButton boton : losBotones) {
            boton.addActionListener(oyente);
        }
    }

    public void muestraBolas(List<Bola> bolasBombo) {
        jpBolas.removeAll();
        for (Bola unaBola : bolasBombo) {
            jpBolas.add(new JLabel(unaBola.getImgBola()));
        }
        jpBolas.updateUI();
    }

    public void borraPantalla() {
        jpBolas.removeAll();
        jpBolas.updateUI();
    }

}
