/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import logica.LogPrincipal;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bAñadir = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bListar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bOrdPorEdad = new javax.swing.JButton();
        bOrdPorApellidos = new javax.swing.JButton();
        bOrdPorNombre = new javax.swing.JButton();
        bOrdPorTieneCoche = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPantalla = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bAñadir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bAñadir.setText("Añadir persona");
        bAñadir.setActionCommand("añadir");

        bModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bModificar.setText("Modificar persona");
        bModificar.setActionCommand("modificar");

        bListar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bListar.setText("Listar");
        bListar.setActionCommand("listar");
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bEliminar.setText("Eliminar persona");
        bEliminar.setActionCommand("eliminar");

        bOrdPorEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOrdPorEdad.setText("Ord. por edad");
        bOrdPorEdad.setActionCommand("ordenar edad");
        bOrdPorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdPorEdadActionPerformed(evt);
            }
        });

        bOrdPorApellidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOrdPorApellidos.setText("Ord. por apellidos");
        bOrdPorApellidos.setActionCommand("ordenar apellidos");
        bOrdPorApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdPorApellidosActionPerformed(evt);
            }
        });

        bOrdPorNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOrdPorNombre.setText("Ord. por nombre");
        bOrdPorNombre.setActionCommand("ordenar nombre");
        bOrdPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdPorNombreActionPerformed(evt);
            }
        });

        bOrdPorTieneCoche.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOrdPorTieneCoche.setText("Ord. tiene coche");
        bOrdPorTieneCoche.setActionCommand("ordenar tiene coche");
        bOrdPorTieneCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdPorTieneCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bOrdPorTieneCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bOrdPorApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bOrdPorEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAñadir)
                            .addComponent(bModificar)
                            .addComponent(bEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bOrdPorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bAñadir, bEliminar, bModificar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEliminar)
                .addGap(39, 39, 39)
                .addComponent(bListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOrdPorEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOrdPorNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOrdPorApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOrdPorTieneCoche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taPantalla.setColumns(20);
        taPantalla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        taPantalla.setRows(5);
        jScrollPane1.setViewportView(taPantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bListarActionPerformed

    private void bOrdPorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdPorEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrdPorEdadActionPerformed

    private void bOrdPorApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdPorApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrdPorApellidosActionPerformed

    private void bOrdPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdPorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrdPorNombreActionPerformed

    private void bOrdPorTieneCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdPorTieneCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrdPorTieneCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bOrdPorApellidos;
    private javax.swing.JButton bOrdPorEdad;
    private javax.swing.JButton bOrdPorNombre;
    private javax.swing.JButton bOrdPorTieneCoche;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPantalla;
    // End of variables declaration//GEN-END:variables

    public void setOyente(LogPrincipal oyente) {
        JButton[] losBotones = {bAñadir, bModificar, bEliminar, bListar, bOrdPorEdad, bOrdPorNombre,
            bOrdPorApellidos, bOrdPorTieneCoche};
        for (JButton boton : losBotones) {
            boton.addActionListener(oyente);
        }
    }

    public void muestra(String texto) {
        taPantalla.setText(texto);
    }

    public void borra() {
        taPantalla.setText("");
    }

}
