/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import logica.Jugada;
import logica.LogPrincipal;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPiedra = new javax.swing.JButton();
        bTijeras = new javax.swing.JButton();
        bPapel = new javax.swing.JButton();
        bOtraJugada = new javax.swing.JButton();
        jlOrdenador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bPiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piedra.png"))); // NOI18N
        bPiedra.setActionCommand("piedra");

        bTijeras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tijeras.png"))); // NOI18N
        bTijeras.setActionCommand("tijeras");

        bPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        bPapel.setActionCommand("papel");

        bOtraJugada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bOtraJugada.setText("<html>O<br>T<br>R<br>A<br><br>J<br>U<br>G<br>A<br>D<br>A");
        bOtraJugada.setToolTipText("");
        bOtraJugada.setActionCommand("otra jugada");
        bOtraJugada.setAlignmentX(0.5F);
        bOtraJugada.setEnabled(false);
        bOtraJugada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bOtraJugada.setMargin(new java.awt.Insets(2, 18, 2, 14));

        jlOrdenador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOrdenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blanco.png"))); // NOI18N
        jlOrdenador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El ordenador saca");

        jlResultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPiedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlOrdenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTijeras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOtraJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOtraJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bTijeras)
                            .addComponent(bPapel)
                            .addComponent(bPiedra))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlOrdenador)
                        .addGap(18, 18, 18)
                        .addComponent(jlResultado)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOtraJugada;
    private javax.swing.JButton bPapel;
    private javax.swing.JButton bPiedra;
    private javax.swing.JButton bTijeras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlOrdenador;
    private javax.swing.JLabel jlResultado;
    // End of variables declaration//GEN-END:variables

    public void setOyente(LogPrincipal oyente) {
        bPiedra.addActionListener(oyente);
        bPapel.addActionListener(oyente);
        bTijeras.addActionListener(oyente);
        bOtraJugada.addActionListener(oyente);
    }

    public void activaPiedra() {
        bPiedra.setEnabled(true);
        bPapel.setEnabled(false);
        bTijeras.setEnabled(false);
        bOtraJugada.setEnabled(true);
    }

    public void activaPapel() {
        bPiedra.setEnabled(false);
        bPapel.setEnabled(true);
        bTijeras.setEnabled(false);
        bOtraJugada.setEnabled(true);
    }

    public void activaTijeras() {
        bPiedra.setEnabled(false);
        bPapel.setEnabled(false);
        bTijeras.setEnabled(true);
        bOtraJugada.setEnabled(true);
    }

    public void JuegoNuevo() {
        bPiedra.setEnabled(true);
        bPapel.setEnabled(true);
        bTijeras.setEnabled(true);
        bOtraJugada.setEnabled(false);
        jlOrdenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blanco.png")));
        jlResultado.setText("Resultado");
        jlResultado.setForeground(Color.black);
    }

    public void verJugadaOrdenador(Jugada jugadaOrdenador) {
        jlOrdenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + jugadaOrdenador.toString() + ".png")));
    }

    public void verResultado(String comprobarGanador) {
        jlResultado.setText(comprobarGanador);
        if (comprobarGanador == "Has ganado") {
            jlResultado.setForeground(Color.green);
        }
        if (comprobarGanador == "Has perdido") {
            jlResultado.setForeground(Color.red);
        }
        if (comprobarGanador == "Empate") {
            jlResultado.setForeground(Color.orange);
        }
    }
}
