/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import oovv.Punto;
import oovv.Zona;

/**
 *
 * @author ÓSCAR SUÁREZ
 */
public class DLeerZona extends javax.swing.JDialog {

    /**
     * Creates new form DAñadir
     */
    public DLeerZona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bValida = new javax.swing.JButton();
        bCancela = new javax.swing.JButton();
        jpEID = new javax.swing.JPanel();
        eAccion2 = new javax.swing.JLabel();
        eDatos5 = new javax.swing.JLabel();
        tfXeid = new javax.swing.JTextField();
        eDatos6 = new javax.swing.JLabel();
        tfYeid = new javax.swing.JTextField();
        jpESI = new javax.swing.JPanel();
        eAccion1 = new javax.swing.JLabel();
        eDatos7 = new javax.swing.JLabel();
        tfXesi = new javax.swing.JTextField();
        eDatos8 = new javax.swing.JLabel();
        tfYesi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bValida.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bValida.setText("valida");
        bValida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        bCancela.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        bCancela.setText("cancela");
        bCancela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        eAccion2.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eAccion2.setText("esquina inferior derecha");

        eDatos5.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eDatos5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eDatos5.setText("X");

        tfXeid.setColumns(5);
        tfXeid.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfXeid.setText("4");

        eDatos6.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eDatos6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eDatos6.setText("Y");

        tfYeid.setColumns(5);
        tfYeid.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfYeid.setText("10");

        javax.swing.GroupLayout jpEIDLayout = new javax.swing.GroupLayout(jpEID);
        jpEID.setLayout(jpEIDLayout);
        jpEIDLayout.setHorizontalGroup(
            jpEIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eAccion2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
            .addGroup(jpEIDLayout.createSequentialGroup()
                .addComponent(eDatos5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfXeid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eDatos6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfYeid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEIDLayout.setVerticalGroup(
            jpEIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEIDLayout.createSequentialGroup()
                .addComponent(eAccion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDatos5)
                    .addComponent(tfXeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eDatos6)
                    .addComponent(tfYeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eAccion1.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eAccion1.setText("esquina superior izquierda");

        eDatos7.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eDatos7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eDatos7.setText("X");

        tfXesi.setColumns(5);
        tfXesi.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfXesi.setText("4");

        eDatos8.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        eDatos8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eDatos8.setText("Y");

        tfYesi.setColumns(5);
        tfYesi.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tfYesi.setText("10");

        javax.swing.GroupLayout jpESILayout = new javax.swing.GroupLayout(jpESI);
        jpESI.setLayout(jpESILayout);
        jpESILayout.setHorizontalGroup(
            jpESILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eAccion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpESILayout.createSequentialGroup()
                .addComponent(eDatos7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfXesi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eDatos8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfYesi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpESILayout.setVerticalGroup(
            jpESILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpESILayout.createSequentialGroup()
                .addComponent(eAccion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpESILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDatos7)
                    .addComponent(tfXesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eDatos8)
                    .addComponent(tfYesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bValida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bCancela))
                    .addComponent(jpESI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpESI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bValida)
                    .addComponent(bCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLeerZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLeerZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLeerZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLeerZona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DLeerZona dialog = new DLeerZona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancela;
    private javax.swing.JButton bValida;
    private javax.swing.JLabel eAccion1;
    private javax.swing.JLabel eAccion2;
    private javax.swing.JLabel eDatos5;
    private javax.swing.JLabel eDatos6;
    private javax.swing.JLabel eDatos7;
    private javax.swing.JLabel eDatos8;
    private javax.swing.JPanel jpEID;
    private javax.swing.JPanel jpESI;
    private javax.swing.JTextField tfXeid;
    private javax.swing.JTextField tfXesi;
    private javax.swing.JTextField tfYeid;
    private javax.swing.JTextField tfYesi;
    // End of variables declaration//GEN-END:variables

    public void setOyente(ActionListener oyente) {
        bCancela.addActionListener(oyente);
        bValida.addActionListener(oyente);
    }

    public void setAccion(String accion) {
        if (accion == "punto") {
            eAccion2.setText("establecer posicion punto");
            jpESI.setVisible(false);
            bValida.setActionCommand("valida punto");
        }
    }

    public Zona getZona() {
        Punto esi = new Punto(Integer.parseInt(tfXesi.getText()), Integer.parseInt(tfYesi.getText()));
        Punto eid = new Punto(Integer.parseInt(tfXeid.getText()), Integer.parseInt(tfYeid.getText()));
        return new Zona(esi, eid);
    }
    
       public Punto getPunto() {
        return new Punto(Integer.parseInt(tfXeid.getText()), Integer.parseInt(tfYeid.getText()));
    }

}
